### ISSUE TITLE
Division Infix operators needed

### ISSUE THREAD

**Issue by magtastic** [Zolang/Zolang#1]
All the operators have support for their mathematical symbols, except division. Add support for `/` as a division operator for consistency sake.

This can be a good "newcomer" issue!

Love this code base, and would definitely love to help.. when I find the time 🙄

**Comment by valdirunars** [comment]
Thange @magtastic 

This should be fixed 👍 

You can find the currently supported infix operators in the updated `README.md` under Documentation -> Language Overview -> Operators

**Comment by valdirunars** [comment]
In RegExRepo.swift  all we had to to is add the case repre (`\\/`) to the operator regex
```swift
public static let `operator` = "\\|\\||&&|or|and|equals|==|(<=)|(>=)|<|>|plus|minus|times|over|modulus|\\*|/|\\+|-|%"
```

Then in the property

```swift
static let operatorPayloads: [String: String]
```

We just needed to add `/` as a key with a value of what it represents in the Zolang compiler

```swift
"/": "over",
```
